capabilities:
  requiresGPU: true
  supportedAccelerators:
    - nvidia.com/gpu
description: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig (Prefill/Decode) for LLMInferenceService.
displayName: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig (Prefill/Decode)
name: kserve-config-llm-multi-node-pd-template-nvidia-cuda
provider: Red Hat, Inc.
versions:
  - image: registry.redhat.io/rhaii-fast/vllm-cuda-rhel9:3.6.0-fast.1@sha256:5f1fb3f23bee2031abffd2216fac5e6458836facc06dc97029aac9a03120195f
    llmInferenceServiceConfig:
      apiVersion: serving.kserve.io/v1alpha2
      kind: LLMInferenceServiceConfig
      metadata:
        annotations:
          opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
          opendatahub.io/runtime-version: 0.26.0+rhaiv.8
          opendatahub.io/supported-topologies: '["workload-multi-node-data-parallel-pd"]'
          openshift.io/description: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig (Prefill/Decode) for LLMInferenceService.
          openshift.io/display-name: vLLM NVIDIA CUDA GPU LLMInferenceServiceConfig (Prefill/Decode)
          serving.kserve.io/well-known-config: "true"
        labels:
          opendatahub.io/config-type: accelerator
        name: 0-26-0-config-llm-multi-node-pd-template-nvidia-cuda
        namespace: opendatahub
      spec:
        prefill:
          template:
            containers:
              - image: registry.redhat.io/rhaii-fast/vllm-cuda-rhel9:3.6.0-fast.1@sha256:5f1fb3f23bee2031abffd2216fac5e6458836facc06dc97029aac9a03120195f
                name: main
          worker:
            containers:
              - image: registry.redhat.io/rhaii-fast/vllm-cuda-rhel9:3.6.0-fast.1@sha256:5f1fb3f23bee2031abffd2216fac5e6458836facc06dc97029aac9a03120195f
                name: main
        template:
          containers:
            - image: registry.redhat.io/rhaii-fast/vllm-cuda-rhel9:3.6.0-fast.1@sha256:5f1fb3f23bee2031abffd2216fac5e6458836facc06dc97029aac9a03120195f
              name: main
        worker:
          containers:
            - image: registry.redhat.io/rhaii-fast/vllm-cuda-rhel9:3.6.0-fast.1@sha256:5f1fb3f23bee2031abffd2216fac5e6458836facc06dc97029aac9a03120195f
              name: main
    minimumRHOAIVersion: "3.6"
    supportLevel: techPreview
    version: 0.26.0+rhaiv.8
